### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by dariocavada** [xsahil03x/before_after#16]
Porting to the null safety version see pull request.

https://github.com/dariocavada/before_after 

if anyone would like to use the null safety version on github right now please add the following to the pubspec.yaml file.
  ```yaml
before_after: 
    git:
      url: https://github.com/dariocavada/before_after.git
```
